name: "catalog"
version: "1.0.0"

profile: "catalog"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  storage_base_url: "{{ env_var('STORAGE_BASE_URL', 'https://data.queria.io') }}"

models:
  catalog:
    +database: catalog
    main:
      raw:
        +materialized: table
      stg:
        +materialized: view
      mart:
        +materialized: table
