name: "catalog"
version: "1.0.0"

profile: "catalog"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  storage_base_url: "https://pub-0292714ad4094bd0aaf8d36835b0972a.r2.dev"

models:
  catalog:
    +database: catalog
    +persist_docs:
      relation: true
      columns: true
    raw:
      +materialized: table
    stg:
      +materialized: view
      +persist_docs:
        relation: true
        columns: false
    mart:
      +materialized: table
      +persist_docs:
        relation: true
        columns: false
