name: "articles"
version: "1.0.0"

profile: "articles"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  articles:
    +database: articles
    main:
      raw:
        +materialized: table
      mart:
        +materialized: view
