"""Auto-generate catalog dbt source files from datasets/catalog/datasources.yml.

Generated files:
  - models/raw/raw_{name}.sql
  - models/raw/_schema.yml
  - models/stg/stg_catalog.sql
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
DATASOURCES_YML = REPO_ROOT / "datasets" / "catalog" / "datasources.yml"
RAW_DIR = REPO_ROOT / "datasets" / "catalog" / "transform" / "models" / "raw"
STG_DIR = REPO_ROOT / "datasets" / "catalog" / "transform" / "models" / "stg"

GENERATED_HEADER = "-- Auto-generated by generate_catalog_sources.py. Do not edit manually."


def load_datasources() -> list[dict]:
    with open(DATASOURCES_YML) as f:
        data = yaml.safe_load(f)
    return data["datasources"]


def generate_raw_sql(name: str) -> str:
    return f"{GENERATED_HEADER}\n{{{{ read_metadata_json('{name}') }}}}\n"


def generate_schema_yml(datasources: list[dict]) -> str:
    models = []
    for ds in datasources:
        models.append({"name": f"raw_{ds['name']}", "description": ds["description"]})
    schema = {"version": 2, "models": models}
    header = "# Auto-generated by generate_catalog_sources.py. Do not edit manually.\n"
    return header + yaml.dump(schema, default_flow_style=False, allow_unicode=True, sort_keys=False)


def generate_stg_catalog(datasources: list[dict]) -> str:
    lines = [GENERATED_HEADER, "{{ config(materialized='table') }}", ""]
    for i, ds in enumerate(datasources):
        if i > 0:
            lines.append("UNION ALL")
        lines.append(f"SELECT * FROM {{{{ ref('raw_{ds['name']}') }}}}")
    lines.append("")
    return "\n".join(lines)


def warn_stale_files(datasources: list[dict]) -> None:
    expected = {f"raw_{ds['name']}.sql" for ds in datasources}
    expected.add("_schema.yml")
    for path in RAW_DIR.iterdir():
        if path.name.startswith("."):
            continue
        if path.name not in expected:
            print(f"WARNING: stale file found: {path.relative_to(REPO_ROOT)}", file=sys.stderr)


def main() -> None:
    datasources = load_datasources()

    RAW_DIR.mkdir(parents=True, exist_ok=True)
    STG_DIR.mkdir(parents=True, exist_ok=True)

    for ds in datasources:
        path = RAW_DIR / f"raw_{ds['name']}.sql"
        path.write_text(generate_raw_sql(ds["name"]))
        print(f"  generated: {path.relative_to(REPO_ROOT)}")

    schema_path = RAW_DIR / "_schema.yml"
    schema_path.write_text(generate_schema_yml(datasources))
    print(f"  generated: {schema_path.relative_to(REPO_ROOT)}")

    stg_path = STG_DIR / "stg_catalog.sql"
    stg_path.write_text(generate_stg_catalog(datasources))
    print(f"  generated: {stg_path.relative_to(REPO_ROOT)}")

    warn_stale_files(datasources)
    print("done.")


if __name__ == "__main__":
    main()
