name: "transform"
version: "1.0.0"

profile: "transform"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  transform:
    +persist_docs:
      relation: true
      columns: true
    tsukuba:
      +database: tsukuba
      raw:
        +materialized: table
      stg:
        +materialized: view
        +persist_docs:
          relation: true
          columns: false
      mart:
        +materialized: view
        +persist_docs:
          relation: true
          columns: false
