transform:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ":memory:"
      database: tsukuba
      schema: main
      threads: 1
      extensions:
        - httpfs
        - ducklake
        - spatial
      attach:
        - path: "ducklake:tsukuba.ducklake"
          alias: tsukuba
          is_ducklake: true
          options:
            DATA_PATH: "tsukuba.ducklake.files/"
            OVERRIDE_DATA_PATH: true
        - path: "ducklake:https://data.oxon-data.work/fdl_experiment/dwh.ducklake"
          alias: dwh
        - path: "ducklake:e_stat.ducklake"
          alias: e_stat
          is_ducklake: true
          options:
            DATA_PATH: "e_stat.ducklake.files/"
            OVERRIDE_DATA_PATH: true
        - path: "ducklake:geo.ducklake"
          alias: geo
          is_ducklake: true
          options:
            DATA_PATH: "geo.ducklake.files/"
            OVERRIDE_DATA_PATH: true
    prd:
      type: duckdb
      path: ":memory:"
      database: tsukuba
      schema: main
      threads: 1
      extensions:
        - httpfs
        - ducklake
        - spatial
      settings:
        s3_url_style: path
        s3_access_key_id: "{{ env_var('R2_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('R2_SECRET_ACCESS_KEY') }}"
        s3_endpoint: "{{ env_var('CLOUDFLARE_ACCOUNT_ID') }}.r2.cloudflarestorage.com"
        s3_region: auto
      attach:
        - path: "ducklake:tsukuba.ducklake"
          alias: tsukuba
          is_ducklake: true
          options:
            DATA_PATH: "{{ env_var('R2_S3_BUCKET_PATH') }}/tsukuba/ducklake.duckdb.files/"
            OVERRIDE_DATA_PATH: true
        - path: "ducklake:https://data.oxon-data.work/fdl_experiment/dwh.ducklake"
          alias: dwh
        - path: "ducklake:e_stat.ducklake"
          alias: e_stat
          is_ducklake: true
          options:
            DATA_PATH: "{{ env_var('R2_S3_BUCKET_PATH') }}/e_stat/ducklake.duckdb.files/"
            OVERRIDE_DATA_PATH: true
        - path: "ducklake:geo.ducklake"
          alias: geo
          is_ducklake: true
          options:
            DATA_PATH: "{{ env_var('R2_S3_BUCKET_PATH') }}/geo/ducklake.duckdb.files/"
            OVERRIDE_DATA_PATH: true
