name: "k_oxon"
version: "1.0.0"

profile: "k_oxon"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  k_oxon:
    +database: k_oxon
    +persist_docs:
      relation: true
      columns: true
    japan_map_for_bi:
      raw:
        +materialized: table
      stg:
        +materialized: view
        +persist_docs:
          relation: true
          columns: false
      mart:
        +materialized: view
        +schema: japan_map_for_bi
        +persist_docs:
          relation: true
          columns: false
