e_stat:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ":memory:"
      database: e_stat
      schema: main
      threads: 1
      extensions:
        - httpfs
        - ducklake
      attach:
        - path: "ducklake:ducklake.duckdb"
          alias: e_stat
          is_ducklake: true
          options:
            DATA_PATH: "ducklake.duckdb.files/"
            OVERRIDE_DATA_PATH: true
        - path: "ducklake:{{ env_var('DWH_DUCKLAKE_PATH', 'https://data.oxon-data.work/fdl_experiment/dwh.ducklake') }}"
          alias: dwh
    prd:
      type: duckdb
      path: ":memory:"
      database: e_stat
      schema: main
      threads: 1
      extensions:
        - httpfs
        - ducklake
      settings:
        s3_url_style: path
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
        s3_endpoint: "{{ env_var('S3_ENDPOINT') }}"
        s3_region: auto
      attach:
        - path: "ducklake:ducklake.duckdb"
          alias: e_stat
          is_ducklake: true
          options:
            DATA_PATH: "s3://{{ env_var('S3_BUCKET') }}/e_stat/ducklake.duckdb.files/"
            OVERRIDE_DATA_PATH: true
        - path: "ducklake:{{ env_var('DWH_DUCKLAKE_PATH', 'https://data.oxon-data.work/fdl_experiment/dwh.ducklake') }}"
          alias: dwh
