"""Dataset initialization: dbt init + queria template generation."""

import os
import re
import shutil
from pathlib import Path

import typer
import yaml
from dbt.cli.main import dbtRunner

from queria import DATASET_YML, DUCKLAKE_FILE, TRANSFORM_DIR
from queria.run import working_directory

_VALID_NAME_RE = re.compile(r"^[a-zA-Z_]\w*$")


def init_dataset(path: Path) -> None:
    """Scaffold a new dataset at the specified path."""
    if path.exists():
        typer.echo(f"Error: {path} already exists", err=True)
        raise typer.Exit(1)

    name = path.name
    if not _VALID_NAME_RE.match(name):
        typer.echo(
            f"Error: '{name}' is not a valid dataset name (alphanumeric and underscores only)",
            err=True,
        )
        raise typer.Exit(1)

    path.mkdir(parents=True)

    # Generate dataset.yml interactively
    typer.echo("Enter dataset metadata:")
    title = typer.prompt("Title")
    description = typer.prompt("Description", default="")
    tags_input = typer.prompt("Tags (comma-separated)", default="")
    tags = [t.strip() for t in tags_input.split(",") if t.strip()] if tags_input else []
    ducklake_url = typer.prompt("DuckLake URL", default="")

    catalog = {
        "title": title,
        "description": description,
        "tags": tags,
        "ducklake_url": ducklake_url,
        "schemas": {"main": {"title": "Main"}},
    }
    dataset_yml_path = path / DATASET_YML
    dataset_yml_path.write_text(
        yaml.dump(catalog, allow_unicode=True, default_flow_style=False, sort_keys=False)
    )

    # Generate transform/ scaffold with dbt init
    typer.echo(f"Running dbt init {name}...")
    with working_directory(path):
        result = dbtRunner().invoke(["init", name, "--skip-profile-setup"])
    if not result.success:
        raise RuntimeError(f"dbt init {name} failed")

    (path / name).rename(path / TRANSFORM_DIR)
    transform_dir = path / TRANSFORM_DIR

    # Remove logs/ generated by dbt init
    logs_dir = path / "logs"
    if logs_dir.exists():
        shutil.rmtree(logs_dir)

    # Remove example models and create raw/stg/mart
    example_dir = transform_dir / "models" / "example"
    if example_dir.exists():
        shutil.rmtree(example_dir)

    for subdir in ["raw", "stg", "mart"]:
        d = transform_dir / "models" / subdir
        d.mkdir(exist_ok=True)
        (d / ".gitkeep").touch()

    # Overwrite dbt_project.yml
    (transform_dir / "dbt_project.yml").write_text(_dbt_project_yml(name))

    # Generate profiles.yml
    (transform_dir / "profiles.yml").write_text(_profiles_yml(name))

    # Generate packages.yml
    repo_root = _find_repo_root(path)
    if repo_root:
        packages_path = os.path.relpath(
            (repo_root / "packages" / "queria_common").resolve(),
            transform_dir.resolve(),
        )
    else:
        packages_path = "../../packages/queria_common"
    (transform_dir / "packages.yml").write_text(_packages_yml(packages_path))

    typer.echo(f"Created dataset: {path}")


def _dbt_project_yml(name: str) -> str:
    return f'''name: "{name}"
version: "1.0.0"

profile: "{name}"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  {name}:
    +database: {name}
    +persist_docs:
      relation: true
      columns: true
    raw:
      +materialized: table
    stg:
      +materialized: view
    mart:
      +materialized: view
'''


def _profiles_yml(name: str) -> str:
    return f'''{name}:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ":memory:"
      database: {name}
      schema: main
      threads: 1
      extensions:
        - httpfs
        - ducklake
      attach:
        - path: "ducklake:{DUCKLAKE_FILE}"
          alias: {name}
          is_ducklake: true
          options:
            DATA_PATH: "{DUCKLAKE_FILE}.files/"
            OVERRIDE_DATA_PATH: true
'''


def _packages_yml(relative_path: str) -> str:
    return f'''packages:
  - local: {relative_path}
'''


def _find_repo_root(start: Path) -> Path | None:
    """Find the repository root by searching upward for a .git directory."""
    current = start.resolve()
    for parent in [current, *current.parents]:
        if (parent / ".git").exists():
            return parent
    return None
