name: "estat"
version: "1.0.0"

profile: "estat"

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  estat:
    +database: estat
    e_stat:
      raw:
        +materialized: view
      mart:
        +materialized: view
